version: '3.8'

services:
  app-prod:
    build:
      context: .
      target: production
      args:
        - API_URL=${API_URL:-http://localhost:8080}
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
      - API_URL=${API_URL:-http://localhost:8080}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
