version: '3.8'

services:
  # Development environment
  app-dev:
    build:
      context: .
      target: development
      args:
        - API_URL=${API_URL:-http://localhost:8080}
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - API_URL=${API_URL:-http://localhost:8080}
    networks:
      - app-network

  # Production environment
  app-prod:
    build:
      context: .
      target: production
      args:
        - NODE_ENV=production
        - API_URL=${API_URL:-http://localhost:8080}
    ports:
      - "80:80"
    environment:
      - API_URL=${API_URL:-http://localhost:8080}
    depends_on:
      - app-dev
    networks:
      - app-network

  # Nginx service for production (if needed separately)
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist/angular-19-i18n:/usr/share/nginx/html
    depends_on:
      - app-prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
